image: debian/stable
oauth: pages.sr.ht/PAGES:RW
packages:
- hut
- ruby-full
- ruby-dev
environment:
  repo: btxx.org
  site: btxx.org
tasks:
- publish: |
    cd $repo
    mkdir build
    sudo gem install bundler
    sudo bundle install
    ruby wruby.rb
- package-site: |
    cd $repo/build
    tar -cvzh . > ../site.tar.gz
- deploy: |
    hut pages publish -d $site --site-config $repo/siteconfig.json $repo/site.tar.gz
- deploy-www: |
    hut pages publish -d www.$site --site-config $repo/siteconfig.json $repo/site.tar.gz
