image: alpine/edge
oauth: pages.sr.ht/PAGES:RW
packages:
- hut
environment:
  repo: btxx.org
  site: btxx.org
submitter:
  git.sr.ht:
    enabled: true
    allow-refs:
      - refs/heads/deploy
tasks:
- package: |
    cd $repo
    cd build
    tar -czf /tmp/site.tar.gz .
- deploy: |
    hut pages publish -d $site --site-config $repo/siteconfig.json /tmp/site.tar.gz
- deploy-www: |
    hut pages publish -d www.$site --site-config $repo/siteconfig.json /tmp/site.tar.gz
